install:
	pip install --upgrade pip && pip install -r requirements.txt

format:
	black *.py

train:
	python train.py

eval:
	python evaluate.py
	echo "## Model Metrics" > report.md
	type .\Results\metrics.txt >> report.md
	echo. >> report.md
	echo ## Confusion Matrix Plot >> report.md
	echo ![Confusion Matrix](./Results/model_results.png) >> report.md

update-branch:
	git config --global user.name "$(USER_NAME)"
	git config --global user.email "$(USER_EMAIL)"
	git add .
	git commit -m "Update with new results" || echo "No changes to commit"
	git push origin HEAD:update

hf-login:
	pip install -U "huggingface_hub[cli]"
	huggingface-cli login --token $(HF) --add-to-git-credential

push-hub:
	huggingface-cli upload TU_USUARIO_HF/Drug-Classification ./App --repo-type=space --commit-message="Sync App files"
	huggingface-cli upload TU_USUARIO_HF/Drug-Classification ./Model /Model --repo-type=space --commit-message="Sync Model"
	huggingface-cli upload TU_USUARIO_HF/Drug-Classification ./Results /Metrics --repo-type=space --commit-message="Sync Results"

deploy: hf-login push-hub

all: install format train eval